services:
    mesclics_admin.beta.html_adder:
        class: MesClics\AdminBundle\BetaHTMLAdder\BetaHTMLAdder

    mesclics_admin.navigation_subscriber:
        class: MesClics\AdminBundle\Event\EventListener\AdminNavigationSubscriber
        arguments:
          - '@mesclics_navigation.navigator'
        tags:
          - { name: kernel.event_subscriber }