services:
#    mesclics_admin.example:
#        class: MesClics\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    mesclics_admin.beta.html_adder:
        class: MesClics\AdminBundle\BetaHTMLAdder\BetaHTMLAdder

    # mesclics_admin.beta.event_listener:
    #     class: MesClics\AdminBundle\Event\EventListener\BetaListener
    #     arguments:
    #         - "@mesclics_admin.beta.html_adder"
    #         - "2018-04-30"
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.response, method: processBeta }
    
#     mesclics_admin.navigation.visited_page_listener:
#         class: MesClics\NavigationBundle\Events\EventListeners\NavigationEventListener
#         tags:
#             - { name: kernel.event_listener, event: kernel.controller, method: test }

    mesclics_admin.navigation_subscriber:
        class: MesClics\AdminBundle\Event\EventListener\AdminNavigationSubscriber
        arguments:
          - '@mesclics_navigation.navigator'
        tags:
          - { name: kernel.event_subscriber }