<?php

namespace MesClics\AdminBundle\Repository;

/**
 * FormManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
